In [20]:
%pip install numpy

import numpy as np

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [21]:
rng = np.random.default_rng(seed=1701)
x2 = rng.integers(10, size=(3, 4, 5))
x1 = rng.integers(10, size=6)
x3 = rng.integers(10, size=(3, 4))

In [22]:
print(x1, x1.ndim, x1.shape, x1.size, x1.dtype, x1.itemsize, x1.nbytes, x2)

[4 3 9 9 2 2] 1 (6,) 6 int64 8 48 [[[9 4 0 3 8]
  [6 3 1 3 7]
  [4 0 2 3 0]
  [0 6 9 4 3]]

 [[5 5 0 8 3]
  [5 2 2 1 8]
  [8 5 3 0 0]
  [8 5 8 5 1]]

 [[6 2 3 1 2]
  [5 6 2 5 2]
  [7 9 3 5 6]
  [0 2 0 2 9]]]


In [23]:
x2[0,1,2] = 42.7
x2

array([[[ 9,  4,  0,  3,  8],
        [ 6,  3, 42,  3,  7],
        [ 4,  0,  2,  3,  0],
        [ 0,  6,  9,  4,  3]],

       [[ 5,  5,  0,  8,  3],
        [ 5,  2,  2,  1,  8],
        [ 8,  5,  3,  0,  0],
        [ 8,  5,  8,  5,  1]],

       [[ 6,  2,  3,  1,  2],
        [ 5,  6,  2,  5,  2],
        [ 7,  9,  3,  5,  6],
        [ 0,  2,  0,  2,  9]]])

In [24]:
# Reversing the array for x2 and x1
# x2[::-1, ::-1, ::-1]
print(x2[1, 1, ::-1])
print("------------------")
print(x1[::-1])

[8 1 2 2 5]
------------------
[2 2 9 9 3 4]


In [25]:
x2[:, 0, :]

array([[9, 4, 0, 3, 8],
       [5, 5, 0, 8, 3],
       [6, 2, 3, 1, 2]])

In [26]:
# changing a subarray 
x3_sub = x3[:2, :2]
x3_sub

array([[4, 0],
       [0, 0]])

In [37]:
x3_sub[0, 0] = 99
x3

array([[99,  0,  0,  3],
       [ 0,  0,  2,  3],
       [ 2,  7,  4,  7]])

The above 2 lines will also modify the original arraty

In [28]:
x3


array([[99,  0,  0,  3],
       [ 0,  0,  2,  3],
       [ 2,  7,  4,  7]])

In [29]:
# We can use the copy() method to create a copy of an array
x3_sub_copy = x3[:2, :2].copy()
x3_sub_copy[0, 0] = 42
x3

array([[99,  0,  0,  3],
       [ 0,  0,  2,  3],
       [ 2,  7,  4,  7]])

In [30]:
x3_sub_copy

array([[42,  0],
       [ 0,  0]])

In [31]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
x = np.arange(9).reshape((3, 3))
2 ** x # Ufunc for exponentiation

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [34]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [35]:
# Trigonometric functions
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])

# Get the real part
real_part = np.real(x)

# Get the imaginary part
imaginary_part = np.imag(x)

# Get the complex conjugate
complex_conjugate = np.conj(x)

# Get the angle (or phase)
angle = np.angle(x)

# Compute the exponential
exponential = np.exp(x)

In [36]:
exponential

array([-13.12878308+15.20078446j, -54.05175886 -7.70489137j,
         7.3890561  +0.j        ,   0.54030231 +0.84147098j])